### ISSUE TITLE
请教下颜兄的 Mac 配置.

### ISSUE THREAD

**Issue by szDarrell** [yanhaijing/awesome-windows#1]
看到这个 repo 得知颜兄要转战 macOS 平台. 冒昧地请教下, 颜兄的 MacBook 准备入手哪个配置的? 谢谢.

**Comment by yanhaijing** [comment]
我这个是公司配的。。。

**Comment by szDarrell** [comment]
Soga。。。 因为我自己准备配 MacBook，所以不知颜兄能否说下具体配置，供参考下，谢谢🙏

**Comment by yanhaijing** [comment]
我这应该是mac 2015那一版，15.5寸，i7，16g 256g，属于高配版，价格 大概 1.3w

**Comment by yanhaijing** [comment]
建议 买个 14寸的就够用了吧。。。存储 感觉 128g不够用

**Comment by szDarrell** [comment]
刚看了下, 目前颜兄你说的这个配置在 apple.cn 上报价 15k 左右... 允许定制的顶配版 21k...  ==!
好像没有 14 吋的吧... 你是想说屏幕较小的那款(13 吋)?

**Comment by yanhaijing** [comment]
我这个不是最新版的mac，最新版的mac都是touchbar那种，我这还是物理键盘的，个人感觉13寸应该够了，这个稍微有点大，主要是携带不方便，但是办公还是爽，你看你是不是要经常带着电脑跑了

**Comment by szDarrell** [comment]
嗯嗯, 上面涉及的两个价位都是 15 款的 MacBook Pro.... 16/17款带 bar 的键盘毛病多啊, 微博和推上吐槽键盘报修的太多了... (/滑稽  /笑cry)

**Comment by yanhaijing** [comment]
你要是需要搬来搬去，那就13寸；否则就15寸，当然你也考虑下价钱，感觉mac还是很贵的

**Comment by szDarrell** [comment]
233333... 敲黑板, 最后一句是重点..... (⊙﹏⊙)b

**Comment by szDarrell** [comment]
话说颜兄, 你工作之外, 自己使用的也是 Mac 么?

**Comment by yanhaijing** [comment]
不是，mac这么贵。。。这电脑下班了不是也能带回家么。。。win我都用了 8年了，最近开始使用mac

**Comment by q1cha0** [comment]
机制的boy😏

**Comment by yanhaijing** [comment]
@q1cha0 乱入的boy😜

**Comment by q1cha0** [comment]
🙈

**Comment by szDarrell** [comment]
@yanhaijing 啊....羡慕......福利棒棒哒🍭

**Comment by szDarrell** [comment]
@yanhaijing 话说颜兄每天上下班背 15 吋的电脑感觉怎么样? 会不会太重啊...... 😂

**Comment by yanhaijing** [comment]
重
